- README.md
Persons -> People, title case for titles, and other small tweaks.
> Style tweaks in readme

- README.md
Better state that before people tries setting it up.
> Clarify that the bot only works on public repositories

- README.md
- app.json
Sorry I missed these in my initial PR
> updating readme

- server.js
Add necessary logging messages. #23
> Add necessary logging messages

- __tests__/github-mention-test.js
- mention-bot.js
- server.js
Get blames for the target branch of the PR instead of assuming `master`
> Get blame for the target branch of the pull request

- README.md
Currently the link does not work as expected in the readme.
> Anchors are lower-case

- README.md
Hello,
I believe ```mention-bot``` can work for whole organization. In is very nice. I added note about that to README. 
Please review my English. I am not a native speaker.
Greetings,
> Add to README about settings for whole GH organization

- CONFIG.md
- __tests__/data/3238.diff
- __tests__/github-mention-test.js
- cache/https---github.com-facebook-react-native-blame-master-Libraries-ReactIOS-NativeMethodsMixin.js
- cache/https---github.com-facebook-react-native-blame-master-Libraries-WebSocket-WebSocket.ios.js
- cache/https---github.com-facebook-react-native-blame-master-Libraries-WebSocket-WebSocketBase.js
- cache/https---github.com-facebook-react-native-blame-master-Libraries-WebSocket-__mocks__-event-target-shim.js
- cache/https---github.com-facebook-react-native-blame-master-Libraries-WebSocket-__tests__-Websocket-test.js
- cache/https---github.com-facebook-react-native-blame-master-website-server-extractDocs.js
- cache/https---github.com-facebook-react-native-pull-3229.diff
- cache/https---github.com-facebook-react-native-pull-3238.diff
- mention-bot.js
- package.json
- server.js
Feel free to be as nit picky as you want!!
- Adds configuration option `maxReviewers` (renamed based on #40, I can take this out if you want. I originally had developed this out and saw that the earlier PR named it differently so conflicts can be managed if it is merged before this one is reviewed)
- Adds configuration option `numFilesToCheck` if anyone desires to check more than 5 files
- Adds configuration option `userWhitelist`. This whitelist is a set of users and the file globs that they want to _always be notified of changes to._
- Adds `minimatch` dependency for file glob checking.
- Adds tests for the added function and some configuration options.
> Additional configuration options

- CONFIG.md
- __tests__/github-mention-test.js
- mention-bot.js
Changes the list of files as a glob to an array so that a user can have a set of unique file globs.
Nit-pick away!
> feat: Changes user file glob an array

- package.json
> Add in engine config to package.json

- githubAuthCookies.js
> Use GHE config for auth cookies

- githubAuthCookies.js
> Github Auth errors are logged

- README.md
- server.js
I added `userBlacklistForPR` option.
This is for to ignore Pull Request which created BOT user or so.
> Add userBlacklistForPR

- app.json
I ***improved* the name** "**`GitHub`**".
*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:
> Improved the name "GitHub"

- __tests__/config-test.js
- config.js
- githubAuthCookies.js
Hope you don't mind 
I saw one of the files had a mix of tabs and spaces so fixed that up
And some of the files had 4 spaces instead of 2 in some of the areas so fixed those up while I was there
> Fix indenting (tabs to spaces), (4 spaces to 2 spaces)

- __tests__/github-mention-test.js
- server.js
Fixing up the small comments from https://github.com/facebook/mention-bot/pull/106
I went for the approach of self-documenting code in the specs rather than commenting each spec for each variable that is passed in
> Fix nit-picking 

- message.js
- server.js
I think it's good to thank the pull_requester (optionally). I just added the pull_requester parameter. 
Test was OK:
(thank-pull-requester)$ npm test
> mention-bot@0.0.1 test /Users/hunkim/gitWorkspace/mention-bot
> flow && jest
No errors!
Using Jest CLI v0.7.1
PASS  __tests__/config-test.js (0.244s)
PASS  __tests__/github-mention-test.js (0.638s)
18 tests passed (18 total in 2 test suites, run time 1.457s)
Also, my demo works fine: http://pr-assistant.herokuapp.com/
> Thank pull requester

- README.md
Added a link to the configuration part.
Sorry that I forget to update this part.
> Update ## Configuring a custom message

- README.md
- server.js
> Add config option to skip already assigned PR's (Closes #118)

- README.md
- server.js
Closes https://github.com/facebook/mention-bot/issues/127
> Add feature of reviewerAssignment

- message.js
Otherwise you might copy the example and think the bot isn't working :)
> Fix custom message example to use valid variable name

- server.js
Typecasting github and updating the licence validity
> typecasing and licence year

- README.md
- __tests__/schedule-test.js
- package.json
- schedule.js
- server.js
Pull request for #119 and #124
> Add feature to delay the comment

- README.md
> document that glob matching is done by minimatch

- README.md
- server.js
Useful when multiple pushes are done. Otherwise it is a bit spammy :)
> Provide an option skipAlreadyMentionedPR

- mention-bot.js
Hey guys, nice tool!
I experienced a buffer exceed for this PR https://github.com/dlang/dmd/pull/6058.
Hence my simple suggestion to increase the size.
If you want to play with this PR, I quickly modified your test hook, s.t. it points to the mentioned PR: http://sprunge.us/diNg
> increase maxBufferSize to 10M

- README.md
- server.js
I hope @tbassetto doesn't mind me making this change, but I needed this fix too to run the bot for a private repo.
Fixes #161
> Fix .mention-bot parsing

- README.md
- server.js
> Parse default config from env

- server.js
...otherwise the sentence just looks a bit sloppy.
> Add period at the end of the default message

- server.js
> Reveal syntax error in parsing .mention-bot file by leaving a comment

- package.json
- server.js
> Display jsonlint error in parsing .mention-bot file with syntax error

- README.md
This PR will update the install steps to match the latest Github UI, so people will not be confused by undocumented steps. It also fixes two (minor) typos in the comments. Thx! 🚀
> Update install to latest Github config, fix typo

- .gitignore
- README.md
- mention-bot.js
- package.json
- server.js
This required upgrading the github client node module, which mostly just needed changing `user` -> `owner` in github calls.
Fixes #195, fixes #192.
> Add option to create review requests

- mention-bot.js
```
Error: Invalid line, should start with something like `diff --git a/`, instead got
--- a/README.md
```
Also just did the naive solution for this,  improvements are welcome
> Fix issue #203 #202 regarding parseDiffFile

- server.js
support branch filter in config file, by default the branch filter will not work so all branches will be monitored
>  support branch filter in the config file

- README.md
- server.js
Add the code sample and comments for branch filter
> Add the code sample and comments for branch filter

- README.md
- server.js
By default the branch filter is empty with zero length, in this case the branch filter will not perform checks.
> Fix the branch filter logic

- .env.example
- .gitignore
- README.md
- docker-compose.yml
`docker-compose` makes it easier to run locally as well as deploy on own server.
> Add docker compose

- mention-bot.js
> Mention-bot breaks while trying to discover team memberships (fixes #242)

- githubAuthCookies.js
> Fix bug where authentication fails due to wrong CSRF token being used (fixes #240)
