- README.md
- app.json
Hey, I implemented the button mentioned in issue #4 - not sure if you wanted it near the top or bottom, so I put it under "How to contribute or run your own bot." The app.json is very basic and I don't have a good source for the mention-bot logo, so it's linked to the github avatars - if a better source is available (along with a desired description, etc) I'd be happy to add it in.
> Implement "deploy to heroku" button

- CONFIG.md
- README.md
- mention-bot.js
- server.js
This PR adds the ability to set repo-specific settings for the bot, by creating a `.mention-bot` file in the base directory of the repo. It also adds one configuration option, `userBlacklist`. Users in the blacklist will never be mentioned by mention-bot.
> Add repo-specific configs

- .babelrc
- .gitignore
- package.json
- run-server.js
- server.js
- Updates dependencies with the object spread transform
- Adds plugins to babelrc
- Updates `npm start` to include the babel transform
Fixes #48
I opted with using Babel to transform the `server.js` instead of `babel-node` because as noted in Babel's documentation it is:
> Not meant for production use
Nit-pick away! :smile:
> fix: Object spread issue

- README.md
- server.js
We use GitHub Enterprise instance. but use `http` protocol and `80` port.
The default's `http` and `443`. will raise some error. like this:
```
connect ECONNREFUSED 192.168.11.29:443
```
> Additional Protocol&Port options

- .gitignore
Removes `server-compiled.js` from the git ignore files now that it is not being used.
> :art: cleanup: Remove compiled server ref in gitignore

- CONFIG.md
- mention-bot.js
- server.js
This PR adds a config option called `requiredOrgs`. In order to be mentioned by the bot, a user will have to be in one of the organizations in the `requiredOrgs` list.
Since this change requires making requests from within `mention-bot.js`, I had to pass in the GitHub API to `guessOwnersForPullRequest()`.
> Implement required organizations in config.

- server.js
If the repo doesn't contain a .mention-bot file this promise will be
rejected with an error from github. `await` will throw when its
promise gets rejected.
Will partly fix #61. I'll post another PR which will fix another issue.
> Catch rejected promise when .mention-bot is missing

- mention-bot.js
Getting a lot of `Error: stdout maxBuffer exceeded.`-errors when
downloading the files. Not sure what a good limit is, but this should be
more than enough.
Also, helps with fixing #61.
> Increase maxBuffer when downloading files

- CONFIG.md
- mention-bot.js
- server.js
Adds a `fileBlacklist` option to the repo config. mention-bot will ignore any files matched by the globs in the blacklist.
> Implement file blacklist.

- __mocks__/cookieJar.js
I got this error when I run `npm test` in my local (because of `$GITHUB_USER`),
```sh
$ npm install
$ npm test
TypeError: /Users/user/js/mention-bot/__tests__/github-mention-test.js: /Users/user/js/mention-bot/mention-bot.js: /Users/user/js/mention-bot/
githubAuthCookies.js: Cannot read property 'logged_in' of undefined
npm ERR! Test failed.  See above for more details.
```
and fix this by adding `__mocks__/cookieJar.js`.
> Mock cookieJar.js manually

- README.md
- server.js
In our case here at @ContaAzul, we run our own mention-bot to support
our private repos.
In that case, it would be great to set a required organization globally
instead of configuring it for each repo (we have lot's of them).
This PR should fix that, don't know if it's the best way of doing this,
though.
I din't found any tests for `requiredOrgs`, so I leave it as is.
> Added a global required organization option

- README.md
- __tests__/github-mention-test.js
- cache/https---github.com-fbsamples-bot-testing-blame-master-hello-world.js
- cache/https---github.com-fbsamples-bot-testing-pull-95.diff
- mention-bot.js
- package.json
Add fallback users to config.
When no other user is found the fallback users will be notified based on file glob.
In a large projects, with many developers and a lot of commits, the `alwaysNotifyForPaths` feature can easily generate too many mentions for some users.
What this PR tries to solve is the ability to configure fallback users when no other user is found.
_side note_
- As I tried to run all the tests, I saw that any test would pass even with failing `expect` cases.
That was due to `Promise`-based tests, so I fixed them by using `pit` instead of `it`for testing.
- I couldn't get flow to work as expected. I got a lot of errors from `babel` when trying to check types. By "googling" it seems that other people experience the same thing in other projects as well …
> Fallback notify users

- __tests__/github-mention-test.js
- mention-bot.js
- server.js
Fixes https://github.com/facebook/mention-bot/issues/104
If the PR is opened on a private repo, we do not want to mention users that are no longer part of that org
`requiredOrgs` does not work in this case unless every one publically lists that they are part of the org.
So now, if the PR is opened on a private repo
We get the list of all members of that org, and filter out any reviewers who do not appear on that list
Thanks :smile:
> Check the org members if the repo is private

- README.md
- server.js
#111 
- Add quick example in the README.md
- Added repoConfig.message based ConfigMessageGenerator.
Without config/no message in config:
With config file:
```
{
"maxReviewers": 5, // Maximum  number of people to ping in the PR message, default is 3
"numFilesToCheck": 10, // Number of files to check against, default is 5
"message": "@pullRequester, cool! @reviewers, please check this out for @pullRequester."
}
```
> Custom message in the config file

- server.js
Was prompting user to expose the `GITHUB_USERNAME` environment variables instead of `GITHUB_USER`
> Reference correct environment variable

- README.md
- __tests__/data/23.webhook
- server.js
Add `skipTitle` configuration option to skip mention-bot if the PR title contains specific text.
Example:
```
{
"skipTitle": "WIP"
}
```
> Add skipTitle Configuration. Fixes #121

- config.js
Makes it easier to deploy mention bot for GHE users without having to
create a custom configuration file and make new docker images.
> Add GHE config via env vars

- server.js
This changes the behavior of mention-bot. Instead of always reading the `.mention-bot` file from the master branch, it uses the `.mention-bot` file from the pull request.
This makes it easy to test new configurations without having to commit on master.
> Read config from pull request

- README.md
- server.js
Our workflow is to open pull requests early so everyone knows who's working on what. When the PR is ready for review, a specific label is added.
This PR adds functionality to set a label with the `withLabel` configuration. This works best when setting the `actions` configuration to `["labeled"]`.
> Add withLabel configuration

- server.js
Reading the word "blame" on the first comment of a pull request
could create a negative impression.
By changing "blame information" to "annotation information" we can
keep up the positive spirit of our contributors.
> Use positive wording when suggesting reviewers

- mention-bot.js
The issue occurs when you add a file with 0 additions or deletions. In this case your diff will look like (see [here](https://patch-diff.githubusercontent.com/raw/brianbao/mention-bot/pull/1.diff):
```
diff --git a/test.js b/test.js
new file mode 100644
index 0000000..e69de29
```
The code pops off the 4th line without checking if the 4th line is a `diff --git`, so you'll get the following error when trying to parse the next file:
```
Error: Invalid line, should start with `diff --git a/`, instead got 
new file mode 100644
```
Additionally, if the diff ends in the empty file, the 4th line will be null, which will throw a `TypeError: Cannot read property 'substr' of undefined`.
> Fix for new files with 0 additions/deletions

- server.js
This PR adds support for setting multiple assignees. It sets __all__ reviewers to be assignees using the `assignees` parameter [GitHub API docs](https://developer.github.com/v3/issues/#parameters-3).
closes #139 
@vjeux I could not find any existing tests for setting the first reviewer as an assignee. Should I also add a test for this?
(I signed the CLA a couple of minutes ago before submitting the PR. Maybe It takes another minute to be registered)
> add support for setting all reviewers as assignees

- server.js
This logs an error to the console and responds with a status 500 when an exception is thrown in the work process.
> Prevent 'Server Timeout' when something goes wrong.

- mention-bot.js
I believe it's the correct method name.
https://mikedeboer.github.io/node-github/#api-orgs-getForUser
> Correct the API to fetch orgs for the specified user

- server.js
This allows the work process to continue when a `.mention-bot` file doesn't exist in the target repo.
> Fixes issue where `.mention-bot` file shouldn't be required

- README.md
- __tests__/github-mention-test.js
- mention-bot.js
This provides a new option, `skipTeamPrs`, to the configuration options for `alwaysNotifyForPaths` and `fallbackNotifyForPaths`.
This option works with GitHub teams. The idea is, if you specify that a team should watch a certain path, but then a member of that team modifies one of their own files, then that team does not need to be included in the resulting comment because they already know about it. However, any other teams the PR creator is not a member of should still get notified.
This only applies to `alwaysNotifyForPaths` and `fallbackNotifyForPaths` since a team will never be mentioned by parsing the blame history. Nevertheless, it's hidden behind a config flag to cut down on the number of HTTP requests made in the case where individual users, rather than teams, are watching …
> Add feature to exclude a team from mentions on PR's made by a member

- server.js
`server.js` checks the existence of the `.mention-bot` config file by comparing the error message strictly with the following string:
```
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
````
However, this URL does not work with the enterprise GitHub. For example, the error message we got is:
```
{"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.6/v3"}'
```
This pull request takes care of this issue by replacing the `===` with `string#match`.
> Fix Error Message Check for GitHub Enterprise

- __tests__/github-mention-test.js
- mention-bot.js
This allows users who just use the `alwaysNotifyForPaths` feature to
avoid setting a GitHub password.
> Use GitHub API for fetching diffs

- mention-bot.js
Github changed their blame HTML structure so the regex parsing authors needed a rehaul
> Fix regex for parseBlame

- mention-bot.js
I was getting the following error for every pull request opened:
```
2017-01-23T22:23:52.887299+00:00 app[web.1]: { [Error: Empty value for parameter 'username': undefined]
2017-01-23T22:23:52.887309+00:00 app[web.1]:   defaultMessage: 'Bad Request',
2017-01-23T22:23:52.887311+00:00 app[web.1]:   code: '400',
2017-01-23T22:23:52.887309+00:00 app[web.1]:   message: 'Empty value for parameter \'username\': undefined',
2017-01-23T22:23:52.887312+00:00 app[web.1]:   status: 'Bad Request',
2017-01-23T22:23:52.887312+00:00 app[web.1]:   headers: undefined }
2017-01-23T22:23:52.887393+00:00 app[web.1]: undefined
````
Took some time to find out it was in this place... 
Seems like the bug was introduced in #198
> fixed error in getOwnerOrgs

- README.md
- server.js
This is useful if you want to utilize request reviews or issue assignment *instead* of commenting. Currently it's only possible to use them *in addition* to commenting.
> Allow disabling commenting

- mention-bot.js
Fixes #209
Javascript is not my strong suite, so this may be wrong. However what I *believe* it will do is use ``getMembersOfOrg`` to fetch a list of every member in every required org then filter the list of owners out by who is contained in that list.
The difference between the new code and the old code is subtle, the old code would iterate over each owner and get a list of organizations that it is a *public* member for. This new code (should) iterate over each organization and get a list of all members that the bot user can see (so public, unless the bot is a member of the org, then public and private).
I believe this should work, though I haven't been able to test it because Github has flagged my bot account for some reason!
> Filter requiredOrgs by a method that understands private members

- server.js
This just adds double-quotes and a period for PR actions in console log to match it up with the format of other log lines.
> Add double quotes around PR actions in log

- __tests__/data/pr229.diff
- __tests__/github-mention-test.js
- mention-bot.js
The new function doesn't need to check as many conditions and in our internal use have found this method to be more stable since we were occasionally hitting edge cases where it was hitting unexpected lines.
> Rewriting the parseDiffFile function for simplicity/stability

- server.js
The previous default message always stated that the history of files in the pull request was analyzed. This is not the case when findPotentialReviewers is set to false - reviewers get mentioned based on settings in the configuration file. This change makes the message more accurate when the setting is disabled.
> Clarify default message

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
To foster a welcoming open source community, a `CONTRIBUTING.md` doc can give first-time contributors tips on how to get started.
In the past Facebook didn't promote including a Code of Conduct when creating new projects, and many projects skipped this important document. Let's fix that too. :)
**why make this change?:**
Facebook Open Source provides a Code of Conduct statement for all
projects to follow, to promote a welcoming and safe open source community.
Exposing the COC via a separate markdown file is a standard being
promoted by Github via the Community Profile in order to meet their Open
Source Guide's recommended community standards.
As you can see, adding this file will improve [the mention-bot community profile](https://github.com/facebook/mention-bot/community)
checklist and …
> Add `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`
